### ISSUE TITLE
Specifying `--resource-types` gives `IndexError: list index out of range`

### ISSUE THREAD

**Issue by rgarner** [SvenskaSpel/har2locust#16]
```
har2locust --resource-types document,xhr performance/an_undergraduate_student_joins.har > performance/an_undergraduate_student_joins.py
```

yields

```
Traceback (most recent call last):
  File "/Users/russ/.pyenv/versions/3.12.0/bin/har2locust", line 8, in <module>
    sys.exit(__main__())
             ^^^^^^^^^^
  File "/Users/russ/.pyenv/versions/3.12.0/lib/python3.12/site-packages/har2locust/__main__.py", line 29, in __main__
    template_values = process(har, args)
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/russ/.pyenv/versions/3.12.0/lib/python3.12/site-packages/har2locust/__main__.py", line 77, in process
    values |= p(entries, args) or {}
              ^^^^^^^^^^^^^^^^
  File "/Users/russ/.pyenv/versions/3.12.0/lib/python3.12/site-packages/har2locust/default_plugins/default_headers.py", line 39, in default_headers
    urlparts = urlsplit(entries[0]["request"]["url"])
                        ~~~~~~~^^^
IndexError: list index out of range
```

Removing the `--resource-types` param generates the script. Also, adding the default `har2locust --resource-types xhr,document,other performance/an_undergraduate_student_joins.har > performance/an_undergraduate_student_joins.py` generates the script with no errors.

**Comment by ivanpuchalka** [comment]
It looks like your HAR file has no resources of those types so after filtering, the entry list ends up empty and causes the error in another plugin. Maybe an explicit error should be thrown if there are no entries after executing an entries processor?

**Comment by cyberw** [comment]
PR very welcome

**Comment by rgarner** [comment]
@cyberw I would like to be able to contribute, but I'm mostly Ruby. My Python will need to get a *lot* better for me not to embarrass myself. I like that it got a *little* better after using this and Locust, and I *love* that Locust makes me *want* to make my Python good enough to do this, so I might be able to do it, but it might take *cough* some time...

**Comment by cyberw** [comment]
I understand :)
